version: '3.7'

networks:
  mantle:
    name: mantle
    ipam:
      config:
      - subnet: 10.30.30.0/24

services:
  mantle-nginx:
    container_name: mantle-nginx
    image: nginx:1.17.6-alpine
    volumes:
    - .:/ws
    - ./build:/usr/share/nginx/html
    ports:
    - 80:80
    networks:
      mantle:
        ipv4_address: 10.30.30.2

  mantle-front:
    container_name: mantle-front
    image: node:10.17.0-alpine
    entrypoint: /bin/sh -c '/ws/build.sh; tail -f'
    working_dir: /ws/front
    volumes:
    - .:/ws
    ports:
    - 3003:3003
    - 6006:6006
    environment:
      HOST: 0.0.0.0
      API_URL_PRO: https://mantle.madesimplegroup.com
      API_URL_DEV: http://10.30.30.3:6006
      SCREENSHOTS: .screenshots
      API_PORT: 6006
      APP_URL: http://10.30.30.2
      APP_PORT_DEV: 3003
    networks:
      mantle:
        ipv4_address: 10.30.30.3

  mantle-hub:
    container_name: mantle-hub
    image: selenium/hub:2.53.1-beryllium
    environment:
      TZ: BRT3BRST,M11.1.6/23:59:59,M2.3.6/23:59:59
    ports:
     - 4444:4444
    networks:
      mantle:
        ipv4_address: 10.30.30.4
    depends_on:
    - mantle-front

  mantle-firefox:
    container_name: mantle-firefox
    image: selenium/node-firefox:2.53.1-beryllium
    environment:
      HUB_PORT_4444_TCP_ADDR: mantle-hub
      TZ: BRT3BRST,M11.1.6/23:59:59,M2.3.6/23:59:59
    ports:
    - 9000
    networks:
      mantle:
        ipv4_address: 10.30.30.5
    depends_on:
    - mantle-front

  mantle-chrome:
    container_name: mantle-chrome
    image: selenium/node-chrome:2.53.1-beryllium
    ports:
    - 9000
    environment:
      HUB_PORT_4444_TCP_ADDR: mantle-hub
      TZ: BRT3BRST,M11.1.6/23:59:59,M2.3.6/23:59:59
    networks:
      mantle:
        ipv4_address: 10.30.30.6
    depends_on:
    - mantle-front

